name: amul_galasy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage:
  firebase_core: any
  cached_network_image: any
  material_floating_search_bar: ^0.3.7
  # carousel_slider: ^4.0.0
  flutter_carousel_slider: ^1.0.9
  dart_code_metrics: ^4.17.1
  flutter_iconly: ^1.0.2
  flutter_staggered_grid_view: ^0.4.0
  change_app_package_name: ^1.1.0
  url_launcher: 6.1.6
  animated_text_kit: ^4.2.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
    - assets/image/
  fonts: 
    - family: JosefinSansBold
      fonts: 
        - asset: assets/fonts/JosefinSans-Bold.ttf
    - family: JosefinSansSemiBold
      fonts: 
        - asset: assets/fonts/JosefinSans-SemiBold.ttf
    - family: JosefinSansMedium
      fonts: 
        - asset: assets/fonts/JosefinSans-Medium.ttf
    - family: JosefinSansRegular
      fonts: 
        - asset: assets/fonts/JosefinSans-Regular.ttf
  uses-material-design: true
  generate: true

